name: talkhands
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.14

  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.1.0

  iconsax_flutter: ^1.0.0
  cupertino_icons: ^1.0.8

  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.2
  connectivity_plus: ^6.1.1
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  tflite: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.5.2
  flutter_dotenv: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/model/best-fp16.tflite
    - assets/model/gesture_recognizer.task

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/applogo_black_transparent.png
  android: true
  ios: true
  web: false
